name: ADOFAI
main: com.github.xenon.adofai.plugin.AdofaiPlugin
version: 1.0
commands:
  adofai:
    permission: command.adofai
    description: command for adofai
permissions:
  command.adofai:
    default: op
    description: permission for activate command.adofai